services:
  - type: worker
    name: property-system-worker
    env: node
    rootDir: .
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8085
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
